config/routes.rb
Rails.application.routes.draw do
  
  get 'uploaders/index'

  get 'uploaders/new'

  get 'uploaders/create'

  get 'uploaders/destroy'
  post "uploaders/filter", to: "uploaders#filter", as: "filter"
  resources :uploaders, only: [:index, :new, :create, :destroy]   

  devise_for :users
  devise_scope :user do
    get '/users/sign_in' => "devise/sessions#new", :as => :login
  end
  get 'home/index'

  devise_for :views
  

  root to: "home#index"
end

app/models/uploader.rb
class Uploader < ActiveRecord::Base
    belongs_to :user
    mount_uploader :attachment, AttachmentUploader   
    serialize :tags
    validates :title,:description,:attachment, presence: true # Validates only for blank in case  
  
    # before_validation :change_string_to_array, on: [:create]


    # def change_string_to_array
    #     if self.tags.present?
    #         tags = self.tags.split(',')
    #     end
    # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :uploaders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def require_login!
    unless current_user
      redirect_to login_path, :notice => 'if you want to add a notice'
    end
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/uploaders_controller.rb
class UploadersController < ApplicationController
  before_filter :require_login!
  def index
    @uploaders = current_user.uploaders
    @tags = current_user.uploaders.pluck(:tags)
    if @tags.present?
      @concatenated = @tags.flatten.uniq
    else
      @concatenated = nil
    end
    # concatenated.each do |tag|
    #   return render json: tag
    # end
  end

  def new
    @uploader = Uploader.new   
  end

  def filter
    tags_data = current_user.uploaders.select { |m| m.tags.include? params[:tag] }
    return render json: tags_data
  end

  def create
    # return render plain: params
    @uploader = Uploader.new(uploader_params)   
         @uploader.user_id = current_user.id
         if params[:uploader][:tags] != ''
          tags = params[:uploader][:tags].split(',')
        else
          tags = nil
         end
         @uploader.tags = tags
      if @uploader.save   
         redirect_to uploaders_index_path, notice: "Successfully uploaded."   
      else   
         render "new"   
      end  
  end

  def destroy
    @uploader = Uploader.find(params[:id])   
      @uploader.destroy   
      redirect_to uploaders_path, notice:  "Successfully deleted."   
  end

  private   
  def uploader_params   
  params.require(:uploader).permit(:title,:description, :attachment)   
end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/uploaders_helper.rb
module UploadersHelper
end

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.email : 'Stranger' %>
<h1>Welcome, <b><%= name %></b> </h1>
<% if current_user.present? %>
<%= link_to "My File List", uploaders_path %>   
<% else %>
<h5> You are not signed in yet! </h5>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>Assignment</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
  <%= csrf_meta_tags %>
</head>
<body class="text-center">
<%= render 'shared/navbar' %>
 <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Assignment Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/uploaders/create.html.erb
<h1>Uploaders#create</h1>
<p>Find me in app/views/uploaders/create.html.erb</p>

app/views/uploaders/destroy.html.erb
<h1>Uploaders#destroy</h1>
<p>Find me in app/views/uploaders/destroy.html.erb</p>

app/views/uploaders/index.html.erb
<div class="container text-left">   

  
<br>   
  
<%= link_to "Create New", new_uploader_path %>   
<br>   
<br>   
  
<table border="3" class="table">   
<% if @uploaders.present? %>
<h2> My Files </h2>
<h4> Find By Tags</h4><span> Click on any tag to get data</span>
<% if @concatenated.present? %>
   <% @concatenated.each do |tag| %>
      <a style="margin:15px; font-size: 20px; cursor:pointer" class="tags" data="<%= tag %>"><span class="badge badge-primary"><%= tag %></span></a>
   <% end %>
<% end %>
      <thead>   
         <tr>   
            <th>Title</th>   
            <th>Description</th>   
            <th>Action</th>   
         </tr>   
      </thead>   
         
      <tbody class="append_here">   
      
         <% @uploaders.each do |uploader| %>   
               <tr>   
                  <td><%= uploader.title %></td>   
                  <td><%=  uploader.description %></td>   
                  <td><a class="CopyClip" style="cursor:pointer" data="<%=  root_url + uploader.attachment_url %>"> Share </a>  <%= link_to "Delete",  uploader, method: :delete %> </td>   
               </tr>  
               
         <% end %>   
      
      </tbody>   
   <% else %>
   <h3> No Record Found! </h3>   
   <% end %> 
</table>   
</div> 
<script type="text/javascript">
$( ".table" ).on( "click",".CopyClip", function() {
   var  copyText = $(this).attr("data");

   alert("Please copy the URL to Share: " + copyText);
         })
$('.tags').click(function(){
   var  tag = $(this).attr('data')
   $.ajax({
      type: "POST",
      url: "/uploaders/filter",
      dataType: "json",
      data: { tag: tag },
      beforeSend: function(){
      },
      complete: function(res){
         var divsToAppend = ''
         var response = res.responseJSON
         if(response.length > 0){
            var last_id = ''
            for(i = 0; i < response.length; i++) {
               
               console.log(i)
               divsToAppend += '<tr>';
               divsToAppend += '<td>' + response[i].title + ' </td>';
               divsToAppend += '<td>' + response[i].description + ' </td>';
               divsToAppend += '<td><a class="CopyClip" style="cursor:pointer" data="<%=  root_url %>'+ response[i].attachment.url +'"> Share </a>  <a rel="nofollow" data-method="delete" href="'+ response[i].id + '">Delete</a> </td>';
               divsToAppend += '</tr>';
            }
            $( ".append_here" ).html(divsToAppend);
            }else{
            $( ".append_here" ).html("Sorry No data found with this tag!");

         }
      }
   });
})
</script>

app/views/uploaders/new.html.erb
<div class="container text-left">   
<% if !@uploader.errors.empty? %>   
   <div>   
         
      <ul>   
         <% @uploader.errors.full_messages.each do |msg| %>   
            <li><%= msg %></li>   
         <% end %>   
<% end %>    
   <%= form_for @uploader, html: { multipart: true,class: "form-horizontal" } do |f| %>   
      <div class="row">
         <div class="col-md-10">
            <div class="form-group">
               <%= f.label :title , :class => "col-sm-4 control-label" %>   
               <%= f.text_field :title %>  
            </div> 
            <div class="form-group">   
               <%= f.label :Description, :class => "col-sm-4 control-label" %>   
               <%= f.text_field :description %>   
            </div>
            <div class="form-group">
               <%= f.label :Tags ,:class => "col-sm-4 control-label"%>   
               <%= f.text_field :tags, :class => "col-sm-6 control-label", :placeholder => "Enter Comma Seperated Values Like: pdf,jpg,etc" %>   
            </div>  
            <div class="form-group">
               <%= f.label :attachment, :class => "col-sm-4 control-label" %>   
               <%= f.file_field :attachment %>   
               <br>  
            </div> 
            <div class="form-group text-left">
               <%= f.submit "Save" , :class => " col-sm-2 btn btn-primary form-control" %> 
            </div>  
         </div>  
      </div>  
   <% end %>   
</div>   
</div>  